### ISSUE TITLE
iOS : Store transaction histories and balance locally

### ISSUE THREAD

**Issue by senagbe** [HTMLCOIN/htmlcoin-ios#10]
Currently client does not store any data locally, so it's empty each time open it.
The app already stored contract locally, it's needed to extend to store history and balance

**Comment by senagbe** [comment]
@longpham2310 please try and stick to the same model as Android as much as possible.

**Comment by vsabolc** [comment]
Killed the app and after killed the internet connections as well. Started the app and logged in - Store transaction and balance was displayed - OK.
