### ISSUE TITLE
iOS: The actual HTML balance is not displayed

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-ios#13]
@senagbe

Steps to reproduce:
- Open the iOS app
- Log in
- Send HTML Coins and Recieve HTML Coins
- The Balance is always 0
- Actually, the Balance will appear, but only later (it needs more than a half hour or a sent transaction)

![balance](https://user-images.githubusercontent.com/4669689/36585905-fcf48638-187f-11e8-8421-76eabdd503a9.png)

**Comment by longpham2310** [comment]
@vsabolc It's fixed. Please test again.

**Comment by vsabolc** [comment]
Tested. The issue has been fixed.
