### ISSUE TITLE
iOS: Tapped on a notification about a Transaction which is confirmed, but when I opened the app, it was still unconfirmed

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-ios#16]
@senagbe

Steps to reproduce:
- Open the iOS app
- Log in
- Allow the notifications
- Make new Transactions
- Wait until at least one of them got confirmed
- Read the notification
- Tap on it
- The app will be loaded
- Check the Confirmed transaction
- In the Activity, it is still waiting for confirmation

![confirmed-unconfirmed](https://user-images.githubusercontent.com/4669689/36891923-6520a1c8-1e03-11e8-9f7b-05b9441349a3.png)

**Comment by senagbe** [comment]
@longpham2310 and @dohaivu any ideas regarding this?

**Comment by vsabolc** [comment]
The same issue can't be reproduced anymore.
