### ISSUE TITLE
IOS: Incorrect Passphrase was not declined, but a new account was created

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-ios#19]
@senagbe 

Steps:
- Start the latest app
- Tap on the IMPORT WALLET
- Enter a totally random text - make sure it is not a valid passphrase
- Tap on the IMPORT button when it become active
- The Create PIN page appear

This is not correct - as there was added a totally incorrect passphrase, so error message should appear and not the Create new user flow should be followed!

**Comment by dohaivu** [comment]
It is the same as https://github.com/HTMLCOIN/htmlcoin-android/issues/30

**Comment by vsabolc** [comment]
Tested. The system allows 12 words. Closing.
