### ISSUE TITLE
iOS: available balance does not subtract pending balance. Available Balance is Not available to use.

### ISSUE THREAD

**Issue by lunamonkey** [HTMLCOIN/htmlcoin-ios#24]
Steps to recreate
Send a large payment with the fee set to the lowest.
Available balance does not update
Unconfirmed balance shows as negative.

Attempt another high value transfer using the amount shown as available.

Error message displays showing insufficient funds when send transfer is attempted.

**Comment by senagbe** [comment]
@vsabolc is this a duplicate? It looks familiar.

**Comment by vsabolc** [comment]
@senagbe Yes, we had already a discussion about this problem. https://github.com/HTMLCOIN/htmlcoin-ios/issues/20

**Comment by senagbe** [comment]
Deleting this as its a known issue and being dealt with in https://github.com/HTMLCOIN/htmlcoin-ios/issues/20
