### ISSUE TITLE
iOS: Opening the app from the Confirmed Transaction notification crashes the app

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-ios#26]
@senagbe

Steps to reproduce:
- Install the app on an iOS device (iPhone X)
- Log in
- Go to the Send screen
- Send a new transaction
- Leave the app in the background, wait until the screen lock activates or turn off the display
- Transaction confirmed notification arrives
- Tap on it
- Tap on open
- Remove the screen lock
- Enter the PIN
- The Send screen will be displayed, but no interaction could be made with the app

![not1](https://user-images.githubusercontent.com/4669689/37036120-fbcc5ff6-214e-11e8-83e7-6f0f1641e8ea.png)
![not2](https://user-images.githubusercontent.com/4669689/37036121-fbe72516-214e-11e8-8f9d-38ed524f2b61.png)
![screenwithoutinteraction](https://user-images.githubusercontent.com/4669689/37036123-fc086ef6-214e-11e8-8b60-df617678289f.png)

**Comment by vsabolc** [comment]
The same issue does not occur anymore.

**Comment by pooranjoshi** [comment]
My wallet app doesn’t open and keep crashing on iPhoneX and have all my coins inside wallet. What to do to recover?
