### ISSUE TITLE
iOS: The displayed HTML COIN address is not the same on the My Wallet page header and in the Activity stream after I make payment

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-ios#27]
@senagbe 

Steps to reproduce:
- Install the iOS app
- Import Wallet (please do not change it or invalidate it)
REDACTED by @senagbe
- Add PIN
- Check the My Wallet page
- Check the displayed HTMLCOIN address - it is
HoAucDxF........
- Go lower and check some Sent transaction
- Check the From address
- It is HmXjs....

So the 2 displayed address are not the same - check the screenshots.

![from](https://user-images.githubusercontent.com/4669689/37042906-ade16546-215f-11e8-8141-9eeed7b85dc1.PNG)
![mywallet-htmlcoinaddress](https://user-images.githubusercontent.com/4669689/37042907-ae033950-215f-11e8-831b-fd9aee4c9d50.PNG)

**Comment by dohaivu** [comment]
@senagbe , @vsabolc , @longpham2310 
I checked both of them are in your wallet
It's normal, you can choose any of 10 your addresses to display by clicking on the plus symbol
And the activity display all transactions from those 10 addresses
