### ISSUE TITLE
iOS: The Push notification was displayed 2-3 times for the same event

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-ios#28]
@senagbe 

Steps to reproduce:
- Open the app
- Login
- Go to Send tab
- Make a Transaction
- Check the displayed notification during you are on the Send page
- New transaction notification will appear 2-3 times
- Wait for the transaction to be approved
- Check the notifications
- The same notification arrived 3 times for the very same event - check the screenshots

![notification1](https://user-images.githubusercontent.com/4669689/37044472-d8fa947e-2163-11e8-8be1-51bd4e34a741.PNG)
![notification2](https://user-images.githubusercontent.com/4669689/37044473-d9259af2-2163-11e8-8db3-ef327e9cf854.PNG)

**Comment by dohaivu** [comment]
This only happens when you transfer coin from one address to another in the same wallet.
I will change logic on server to fix this case.

**Comment by dohaivu** [comment]
Fixed and deployed

**Comment by vsabolc** [comment]
Tested. The issue has been fixed.
