### ISSUE TITLE
iPhoneX navigationBar need to improve

### ISSUE THREAD

**Issue by longpham2310** [HTMLCOIN/htmlcoin-ios#4]
Currently, the navigation bar on iPhone X overlaps with the status bar. It's really hard to tap into the navigation bar button.

**Comment by senagbe** [comment]
@vsabolc Please document the iPhone X issues here with your suggestions.

**Comment by longpham2310** [comment]
@senagbe I have to deal with the safe area for iPhone X. Because they haven't implemented for iPhone X yet.
- I also need the designer give me the high-resolution assets `@3x` for iPhone X. Currently the assets he gave me isn't standard.

**Comment by longpham2310** [comment]
<img width="434" alt="screenshot 2018-02-22 18 43 25" src="https://user-images.githubusercontent.com/2587012/36536651-5917ca9a-1800-11e8-90ce-abd6866b9ec8.png">
<img width="357" alt="screenshot 2018-02-22 18 28 44" src="https://user-images.githubusercontent.com/2587012/36536666-639f3b4c-1800-11e8-85fe-6d413a5c5743.png">

**Comment by longpham2310** [comment]
@senagbe We just only need the design for iPhone 8. I will deal with the safe area to make it better on iPhone X.
<img width="250" alt="screenshot 2018-02-22 18 49 59" src="https://user-images.githubusercontent.com/2587012/36536942-3f5d135c-1801-11e8-9ca2-b507feb71054.png">
Here is an example the navigation bar & tab bar. If we applied it to the iPhone 5. The display isn't good.  We also need the define for selected, unselected state for the tab bar.

**Comment by vsabolc** [comment]
@senagbe At this moment the biggest problem is that the app is too close to the top part, so the BACK navigation button does not work correctly - it is hard to tap on it to get it working after 1 tap.

The whole top part should be moved about 0.5cm lower and the navigation issue will go away, also the Titles will become more visible and not stuck to the top.

**Comment by vsabolc** [comment]
Tested. The redesign has been applied and it is a lot easier usable.
