### ISSUE TITLE
iOS: Once the insufficient fund modal appears at a transaction attempt, it will be displayed all the time for any transaction

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-ios#49]
@senagbe 

Steps to reproduce:
- Install the latest iOS app (0.9.1 (108)) on iPhone X
- Log in
- Copy an address for a new Transaction (HjoYYqymHJEdQ7kxYVbyHMHVj7qzPkKoGQ)
- Go to the Send screen
- Add the address
- Add an amount
- Set the fee
- Send it
- Do not wait until it got confirmation
- Try to send one more time
- Insufficient modal appears (there is a discussion already about it in https://github.com/HTMLCOIN/htmlcoin-ios/issues/20)
- Make navigation in the app
- View older transactions
- Go to the Send screen after the previous transaction has been completed
- Try the Transaction again
- Insufficient modal appears
- No matter which data is changed now, always the Insufficient modal appears

![insuff](https://user-images.githubusercontent.com/4669689/37511304-a4874a50-28fe-11e8-9ddc-472e24e4a536.png)

**Comment by vsabolc** [comment]
Update: I reinstalled the app, logged in again and none of the transactions were displayed and 0 was displayed on the actual Balance. Re-importing the Wallet solved the problem.

**Comment by longpham2310** [comment]
@vsabolc Fixed. Please test again.

**Comment by vsabolc** [comment]
Tested. The issue has been fixed.
