### ISSUE TITLE
Update to a more legible font

### ISSUE THREAD

**Issue by kade119** [HTMLCOIN/htmlcoin-ios#5]
The current font used for the address in the wallet UI is somewhat hard to read, I recommend using a sans-serif font.  Suggesting just a simpler font on the address and amount content.

roboto, lato, tahoma

**Comment by longpham2310** [comment]
@senagbe I think we need to discuss about it or assign it to the designer.

**Comment by senagbe** [comment]
@kade119 which font would work considering the brand guidelines?

**Comment by kade119** [comment]
Work sans light, work sans or roboto family

**Comment by kade119** [comment]
With the latest release, the app opens using a sans font then reverts back to the serif

**Comment by longpham2310** [comment]
@kade119 We haven't changed the font yet.

**Comment by vsabolc** [comment]
Tested. It is visually improved. It is easier to read.
