### ISSUE TITLE
iOS: Created a new Wallet added funds by a Transaction, sent back all the available money and the Balance is not refreshed even when the Transaction is confirmed

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-ios#52]
@senagbe

Steps to reproduce:
- Install the latest iOS app (0.9 (108)) on iPhone 6 (10.3.3)
- Create a new Wallet
- Send some fund to it (6.33 ~ 6.32999992)
- Go to the Send screen
- Send the Whole amount back to the previous address
- Wait until it is Confirmed
- This Wallet should not have any available Coins now
- Go to then Wallet screen
- The Transaction history is updated, but the Available Balance still not

![avbal](https://user-images.githubusercontent.com/4669689/37516912-090e5c28-2910-11e8-8683-4bd9b2052da0.png)

**Comment by longpham2310** [comment]
It's fixed. Please test again.

**Comment by vsabolc** [comment]
Tested. It is fixed.
