### ISSUE TITLE
Logout: Change the button name or the text message what is displayed on the popup

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-ios#6]
@senagbe 

Steps to reproduce:
- Open the app
- Login
- Tap on Profile
- Tap on Log Out
- Warning popup will be displayed 
"You are about to exit your account. All account data will be erased from the device. Please make sure you have saved back-ups of your Passphrase and required Contracts."
- The text and the button are not consistent - button is saying Log Out, text is saying Exit - use only one of the and show it on both place - on button and in the text as well.

![logout](https://user-images.githubusercontent.com/4669689/36383901-d417da3e-158d-11e8-9620-fe2f6ed94af2.PNG)

**Comment by senagbe** [comment]
@long please correct the text to say "logout".

**Comment by vsabolc** [comment]
Tested. The message has been changed.
