### ISSUE TITLE
Send: Field description or Name is missing on the Send page - under the Amount field

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-ios#7]
@senagbe 

Steps to reproduce:
- Open the app
- Login
- Tap on Send
- Check the page
- Check the section under the Amount
- There is displayed a slider with values from 0.00001 to 1
- For the new users this does not mean anything - add a field name like under at the Fee field

 **Issue present on Android as well** 

![send](https://user-images.githubusercontent.com/4669689/36383926-e2c0d450-158d-11e8-8539-35ebf652ac7d.PNG)

**Comment by longpham2310** [comment]
@senagbe It isn't issued. Please review it.

**Comment by senagbe** [comment]
This isn;t an issue currently as this is a for of the QTum wallet with a reskinning and a shift to the HTML chain.
