### ISSUE TITLE
iOS: The Android app has lot more options in the Profile than the iOS app

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-ios#70]
@senagbe

Steps to reproduce:
- Open the Android and the iOS app
- Log in to both with different accounts
- Go to the Profile screen
- The Android app has a lot more options in it

Differences:
iOS does not have Touch ID; Theme Switch; RESET AND WIPE
Android does not have Log Out option

![diff](https://user-images.githubusercontent.com/4669689/38614952-4042e310-3d8f-11e8-934a-1672eb4989a6.png)

**Comment by longpham2310** [comment]
@vsabolc On iOS. The TouchID row will show if that device is supported fingerprint.

**Comment by vsabolc** [comment]
In that case, this can be closed.
