### ISSUE TITLE
iOS: The design has to be improved for the My Published Contracts screen

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-ios#71]
@senagbe

Steps to reproduce:
- Open the iOS app
- Log in
- Go to the Profile
- Tap on the Smart Contracts
- Tap on My Published Contracts
- The screen is different from the other screens
- The top menu color is different, the arrow is displayed too high
- It should be improved in according to the other Smart Contract pages

![contracts](https://user-images.githubusercontent.com/4669689/38615546-58e02200-3d91-11e8-931b-c7d0d95dd322.png)

**Comment by longpham2310** [comment]
fixed in 0.9.1(110)

**Comment by vsabolc** [comment]
Tested. The issue has been fixed.
