### ISSUE TITLE
iOS: Login screen is different from the login screen on Android

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-ios#8]
@senagbe 

Steps to reproduce:
- Install the app on both platform
- Login
- Tap on the Home button
- Start both app
- Tap on Login button
- Check the displayed page and compare them on iOS and Android
- They are different - they have different title
- iOS has Touch ID popup displayed - Android does not have (ok, this can be an OS dependent thing - so we can consider not issue)
- Android has field help displayed under the PIN placeholders - iOS does not have

Login pages should have the same design

![login-android](https://user-images.githubusercontent.com/4669689/36479751-1767daf0-170a-11e8-8fc2-b76b757937e0.PNG)
![login-ios](https://user-images.githubusercontent.com/4669689/36479752-17896ea4-170a-11e8-9a03-5009153683d5.PNG)
![login-ios2](https://user-images.githubusercontent.com/4669689/36479753-17a8f09e-170a-11e8-9e9e-d4d5e82a1a18.PNG)

**Comment by senagbe** [comment]
I think this is a non-issue
